CREATE TABLE FAMILIA
(
	IDFAMILIA SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(50),
	DESCRIPCION VARCHAR(80)
);
INSERT INTO FAMILIA (NOMBRE, DESCRIPCION) VALUES ('BEBIDAS','TODO BEBIDAS');
INSERT INTO FAMILIA (NOMBRE, DESCRIPCION) VALUES ('LÁCTEOS','TODO LÁCTEOS');

SELECT * FROM FAMILIA;

CREATE TABLE CATEGORIA

(
	IDCATEGORIA SERIAL PRIMARY KEY,	
	NOMBRE VARCHAR(30),
	IDFAMILIA INT
);


INSERT INTO CATEGORIA (NOMBRE, IDFAMILIA) VALUES ('GASEOSAS',1);
INSERT INTO CATEGORIA (NOMBRE, IDFAMILIA) VALUES ('JUGOS',1);
INSERT INTO CATEGORIA (NOMBRE, IDFAMILIA) VALUES ('LECHE',2);
INSERT INTO CATEGORIA (NOMBRE, IDFAMILIA) VALUES ('QUESO',2);

CREATE TABLE CLIENTE
(
	IDCLIENTE SERIAL PRIMARY KEY,
	NOMBRES VARCHAR(30),
	APELLIDOS VARCHAR(80),
	DNI VARCHAR(8),
	CELULAR VARCHAR(15),
	DIRECCION VARCHAR(50)
);

INSERT INTO CLIENTE (NOMBRES,APELLIDOS,DNI,CELULAR,DIRECCION) VALUES ('PEPITO','PEREZ','12121212','123456789','AV.Central');

SELECT * FROM CLIENTE;

CREATE TABLE PROVEEDOR
(
	IDPROVEEDOR SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30),
	RUC VARCHAR(11)
);

INSERT INTO PROVEEDOR (NOMBRE,RUC) VALUES ('GRORIA','20102010');

SELECT * FROM PROVEEDOR;

CREATE OR REPLACE VIEW VISTA1
AS 
SELECT C.IDCATEGORIA, C.NOMBRE, F.NOMBRE AS FAMILIA, F.IDFAMILIA
FROM CATEGORIA C JOIN FAMILIA F
ON C.IDFAMILIA=F.IDFAMILIA

SELECT * FROM VISTA1;


DELETE FROM cliente
WHERE idcliente IN (4);
